### ISSUE TITLE
Failed to connect - BMS 

### ISSUE THREAD

**Issue by lalyko** [mletenay/home-assistant-pylontech#3]
Hi mletenay,
 thank for this great pylontech extension!!! I've just installed it and tried to connect to my pylontech bms (SC0500).
But the connection failed! I've changed the logging for the pylontech component to debug and retrieved the info response in the home assistant log the output of the info command, but nothing else. Also there is no logging of the conneaction failure ...

Maybe You can give me a hint to get more informations of the failure ... for futher analysis? 

Thanks & regards,
Robert  

![connect-to-pylontech-failed-20230423](https://user-images.githubusercontent.com/85667665/233837106-3e65caf9-36b4-4aea-8dc4-b7009184e8d0.png)
[_homeassistant_logs_20230423.txt](https://github.com/mletenay/home-assistant-pylontech/files/11303562/_homeassistant_logs_20230423.txt)

**Comment by mletenay** [comment]
It smells like the output is slightly different to my (probably firmware version), I'll investigate it ...

**Comment by mletenay** [comment]
I made the "info"  command more robust to better tolerate different firmwares. 
Can you try again ?

**Comment by lalyko** [comment]
Thanks, now I'm one step futher ... the connection works, but a configruation error is thrown.
![Home Assistant - Logs 2023-04-26 09_01_08​ ](https://user-images.githubusercontent.com/85667665/234495996-950a1765-19a0-478d-b5b6-87f58e6046d2.png)
[home-assistant_2023-04-26T06-57-03.608Z.log](https://github.com/mletenay/home-assistant-pylontech/files/11329954/home-assistant_2023-04-26T06-57-03.608Z.log)
